### ISSUE TITLE
support flashrom

### ISSUE THREAD

**Issue by ladyada** [adafruit/Circuit_Pyrate#2]
https://www.flashrom.org/Supported_hardware#USB_Devices

by request!
https://fosstodon.org/@SamantazFox@infosec.exchange/110391372621447393

**Comment by tannewt** [comment]
Source: https://review.coreboot.org/plugins/gitiles/flashrom/+/refs/heads/master/buspirate_spi.c

**Comment by SamantazFox** [comment]
Thank you!

**Comment by SamantazFox** [comment]
I have no compatible board atm, but I'm planning to buy some Feather M4 Express CAN when they're back in stock ^^
